---
- hosts: api
  remote_user: root
  gather_facts: no
  tags: ['always']

  # Ansible requires python2, which is not installed by default on Ubuntu Xenial
  pre_tasks:
    - raw: apt-get -y install python-minimal aptitude
    # action: setup will gather facts after python2 has been installed
    - action: setup

- name: Prepare API instance
  hosts: api
  remote_user: root

  vars:
    deploy_user: deploy

  roles:
    - { role: base }
    - { role: ssh }
    - { role: swap-space }
    - { role: ntp }
    - { role: deploy_user }
    - { role: maven }
    - { role: api }
