---
- hosts: kafka
  remote_user: root
  gather_facts: no
  tags: ['always']

  # Ansible requires python2, which is not installed by default on Ubuntu Xenial
  pre_tasks:
    - raw: apt-get -y install python-minimal aptitude
    # action: setup will gather facts after python2 has been installed
    - action: setup

- name: Prepare Apache Kafka instance
  hosts: kafka
  remote_user: root

  vars:
    deploy_user: kafka
    zookeeper_hosts_group: zookeeper-kafka
    kafka_topic_name: flak-example

    # used by telegraf / influxdb
    telegraf_enabled: true
    telegraf_influxdb_host: http://138.68.74.62:8086
    telegraf_node_type: kafka
    telegraf_influx_username: flak
    telegraf_influx_password: 2Y27VT39o8dnHk7oRBNv4En7jCAvhVDnavFnqoQ2

  roles:
    - { role: base }
    - { role: ssh }
    - { role: swap-space }
    - { role: ntp }
    - { role: deploy_user }
    - { role: telegraf }
    - { role: zookeeper, tags: ['zookeeper'] }
    - { role: kafka, tags: ['kafka'] }
