---
kafka_version: "0.10.2.0"
kafka_scala_version: "2.11"
kafka_source_dir: "kafka_{{ kafka_scala_version }}-{{ kafka_version }}"
kafka_installation_dir: "/home/{{ deploy_user }}"
kafka_home: "{{ kafka_installation_dir}}/kafka"
kafka_tar: "{{ kafka_source_dir }}.tgz"
kafka_mirror_url: "http://mirror.dkd.de/apache/kafka/{{ kafka_version }}/{{ kafka_tar }}"
kafka_log_dir: "/var/log/kafka"
kafka_broker_id: "{{ play_hosts.index(inventory_hostname) }}"
kafka_partitions_per_topic: 1
kafka_topic_name: "ioth"

# turn an array of hosts to a comma separated string of hosts
# [host1, host2] => "host1:2181,host2:2181"
# zookeeper_hosts: "{{ ','.join([host + ':2181' for host in play_hosts]) }}"
zookeeper_hosts: "{{ groups[zookeeper_hosts_group] | map('regex_replace', '^(.*)$', '\\g<1>:2181') | join(',') }}"
